# frozen_string_literal: true

source 'http://rubygems.org'

gemspec

group :development do
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.82'
  gem 'rubocop-performance', '~> 1.26'
  gem 'rubocop-rspec', '~> 3.9'
  gem 'simplecov', '~> 0.21'
  gem 'webmock', '~> 3.26'
end
